# Build stage
FROM node:latest AS build
WORKDIR /build

COPY app/package.json package.json
COPY app/package-lock.json package-lock.json
RUN npm install

COPY app/public/ public
COPY app/src/ src
RUN npm run build

# Production stage
FROM nginx:alpine
COPY --from=build /build/build/ /usr/share/nginx/html
# Expose the default HTTP port for Nginx (port 80)
EXPOSE 80
# Start Nginx and keep the container running
CMD ["nginx", "-g", "daemon off;"]
