# Specify what version of python to use.
FROM python:latest

# Set the working directory.
WORKDIR /code

# Copy the requirements file into the working directory.
COPY ./requirements.txt /code/requirements.txt

# Install the dependencies in the requirements file.
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

# Copy the scripts to the working directory.
COPY ./app /code/app

# Start the server
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "3001"]